# Generated by Django 5.0.3 on 2024-03-18 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='send',
            name='img',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='send',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
